apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: registry-vpc.cn-zhangjiakou.aliyuncs.com/k8s-jenkins/spring-cloud:1.0.1-alpine
        ports:
        - name: http
          containerPort: 8080